version: '2.4.5.{build}'

# Do not build on tags (GitHub only)
skip_tags: true
clone_depth: 1

image:
  - Ubuntu1604  #previously 1604

branches:
  only:
    - master     

stack:
  python 3.8

#environment:
#  GITHUB_TOKEN:
#    secure: 9UB76Z8mCWYt1u7Ci2fPVNiI3iK3LzTuIPhtNGBbxKP7YOPaUuq2yHxRjIfRPEAx
#  UPLOADTOOL_BODY:
#    "WARNING: pre-release builds may not work. Use at your own risk.â€


environment:
  ARTISAN_OS: linux
#  python: 3.8 # NOTE: on update, update also the var PYTHON_PATH in src/build-linux.sh
  PYTHON: $HOME/venv3.8
install:
#  - ls ./.ci
#   don't know why the shell files lost execution permission when shifting to the new-builds repo
  - chmod 777 ./.ci/*.sh
#  - tree -d -L 5 '/home/appveyor/'  > tree.txt
#  - 7z --help
  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
  - .ci/install-${ARTISAN_OS}.sh
build_script:
#   don't know why the shell files lost execution permission when shifting to the new-builds repo
  - chmod 777 src/*.sh
  - .ci/script-${ARTISAN_OS}.sh
#   this is a repo specific path!! 
#  - ls '/home/appveyor/projects/new-builds/src'
#  - ls '/home/appveyor/virtualenv/python3.8/lib/python3.8/site-packages'
  - pwd
artifacts:
#  - path: 'tree.txt'
  - path: 'src/artisan-*.deb'
#  - path: 'src/artisan-*.rpm'

#deploy_script:
#  - cd src
#  - cmd: curl -L -O https://github.com/rpaulo/uploadtool/raw/master/upload.sh
#  - export UPLOADTOOL_BODY="WARNING pre-release builds may not work. Use at your own risk."
#  - export UPLOADTOOL_ISPRERELEASE=true
#  - cmd: bash upload.sh artisan-*.deb
#  - cmd: bash upload.sh artisan-*.rmp
